allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - "@lucide/vue@1.34.0"
  - eslint@10.9.1
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - vite@6.4.1
  - chokidar@4.0.3
